name: qrlogin
description: "A new Flutter package project."
version: 0.0.2
homepage: "https://github.com/manandharsudhir/qrloginegw"
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  built_collection: ^5.1.1
  dio: ^5.4.0
  ferry: ^0.16.0+1
  ferry_store: ^0.5.3+1
  get_it: ^8.2.0
  gql_dio_link: ^1.0.1+1
  gql_http_link: ^1.0.1+1
  uuid: ^4.3.3
  gql_code_builder_serializers: ^0.1.0
  gql_websocket_link: ^2.0.1


dependency_overrides:
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.1.11  
  ferry_generator: ^0.12.0
  json_serializable: ^6.8.0
  freezed: ^3.0.6