// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:gql_code_builder_serializers/gql_code_builder_serializers.dart'
    show OperationSerializer;
import 'package:qrlogin/infra/service/graphql/__generated__/qr_login.data.gql.dart'
    show
        GDeviceAuthData,
        GDeviceAuthData_deviceAuth,
        GaddDeviceData,
        GaddDeviceData_addDevice,
        GaddDeviceData_addDevice_openIddictResponseDto;
import 'package:qrlogin/infra/service/graphql/__generated__/qr_login.req.gql.dart'
    show GDeviceAuthReq, GaddDeviceReq;
import 'package:qrlogin/infra/service/graphql/__generated__/qr_login.var.gql.dart'
    show GDeviceAuthVars, GaddDeviceVars;
import 'package:qrlogin/infra/service/graphql/__generated__/schema.schema.gql.dart'
    show
        GAddDeviceInput,
        GAddPackageRequestInput,
        GAdminDeleteApplicationInput,
        GAdminGenerateTokenInput,
        GAdminPackageCreateInput,
        GAdminPackageDeleteInput,
        GAdminPackageUpdateInput,
        GAdminSetBookPriceInput,
        GAdminSetUserPasswordInput,
        GAdminStoreBookDeleteInput,
        GAdminUpdateApplicationInput,
        GAdminUpdateUserInput,
        GAdminUserDtoFilterInput,
        GApplyPolicy,
        GBookRoleEnum,
        GBooleanOperationFilterInput,
        GCreateOwnApplicationInput,
        GCreateRoleScopeInput,
        GCreateScopedRoleInput,
        GDateTime,
        GDeleteOwnApplicationInput,
        GDeleteRoleScopeInput,
        GDeleteScopedRoleInput,
        GEditPackageRequestInput,
        GFeedDtoFeedType,
        GLongOperationFilterInput,
        GOpenIddictResponseDtoInput,
        GOrgCreateUserActionEnum,
        GOrgCreateUserInput,
        GOrgCreateUserWizardInput,
        GOrgDeleteUserInput,
        GOrgSendSignUpNotificationInput,
        GOrgSetCpanelUserIdInput,
        GOrgSetUserRolesInput,
        GOrgSetUserStatusInput,
        GOrgSetUserTranslationRoleInput,
        GOrgUpdateUserInput,
        GOrgUserStatus,
        GOrganizationLevel,
        GSortEnumType,
        GStringOperationFilterInput,
        GSubscriptionBookDtoBookType,
        GSubscriptionCatchUpInput,
        GSubscriptionCreateInput,
        GSubscriptionDeleteInput,
        GSubscriptionFacebookConnectInput,
        GSubscriptionPauseInput,
        GSubscriptionResumeInput,
        GSubscriptionUpdateInput,
        GSubscriptionsSetDeliveryOptionsInput,
        GSubscriptionsUpdateFeedInput,
        GTimeSpan,
        GURL,
        GUUID,
        GUpdateOwnApplicationInput,
        GUpdateRoleScopeInput,
        GUpdateUserCommandInput,
        GUserDtoSortInput,
        GUserFilterInput;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GAddDeviceInput,
  GAddPackageRequestInput,
  GAdminDeleteApplicationInput,
  GAdminGenerateTokenInput,
  GAdminPackageCreateInput,
  GAdminPackageDeleteInput,
  GAdminPackageUpdateInput,
  GAdminSetBookPriceInput,
  GAdminSetUserPasswordInput,
  GAdminStoreBookDeleteInput,
  GAdminUpdateApplicationInput,
  GAdminUpdateUserInput,
  GAdminUserDtoFilterInput,
  GApplyPolicy,
  GBookRoleEnum,
  GBooleanOperationFilterInput,
  GCreateOwnApplicationInput,
  GCreateRoleScopeInput,
  GCreateScopedRoleInput,
  GDateTime,
  GDeleteOwnApplicationInput,
  GDeleteRoleScopeInput,
  GDeleteScopedRoleInput,
  GDeviceAuthData,
  GDeviceAuthData_deviceAuth,
  GDeviceAuthReq,
  GDeviceAuthVars,
  GEditPackageRequestInput,
  GFeedDtoFeedType,
  GLongOperationFilterInput,
  GOpenIddictResponseDtoInput,
  GOrgCreateUserActionEnum,
  GOrgCreateUserInput,
  GOrgCreateUserWizardInput,
  GOrgDeleteUserInput,
  GOrgSendSignUpNotificationInput,
  GOrgSetCpanelUserIdInput,
  GOrgSetUserRolesInput,
  GOrgSetUserStatusInput,
  GOrgSetUserTranslationRoleInput,
  GOrgUpdateUserInput,
  GOrgUserStatus,
  GOrganizationLevel,
  GSortEnumType,
  GStringOperationFilterInput,
  GSubscriptionBookDtoBookType,
  GSubscriptionCatchUpInput,
  GSubscriptionCreateInput,
  GSubscriptionDeleteInput,
  GSubscriptionFacebookConnectInput,
  GSubscriptionPauseInput,
  GSubscriptionResumeInput,
  GSubscriptionUpdateInput,
  GSubscriptionsSetDeliveryOptionsInput,
  GSubscriptionsUpdateFeedInput,
  GTimeSpan,
  GURL,
  GUUID,
  GUpdateOwnApplicationInput,
  GUpdateRoleScopeInput,
  GUpdateUserCommandInput,
  GUserDtoSortInput,
  GUserFilterInput,
  GaddDeviceData,
  GaddDeviceData_addDevice,
  GaddDeviceData_addDevice_openIddictResponseDto,
  GaddDeviceReq,
  GaddDeviceVars,
])
final Serializers serializers = _serializersBuilder.build();
